[package]
name = "consistent-hashing-ring"
version = "0.1.0"
authors = ["yuer1727 <yuer1727@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
